# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_influencelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalFraction',
            fields=[]
        ),
        migrations.CreateModel(
            name='HistoricalPoliticalFraction',
            fields=[]
        ),
        migrations.AddField(
            model_name='historicalpoliticalfraction',
            name='history_user',
            field=models.IntegerField(null=True),
            
        ),
        
    ]
