# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 16:52
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20170313_1635'),
    ]

    operations = [
            migrations.AlterField(
            model_name='action',
            name='helpers',
            field=models.ManyToManyField(blank=True, help_text='People who you excpect help from on this action. (warning: they might betray you.) (Hold down Ctrl to select multiple choices.)', related_name='allowedHelp', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='action',
            name='willpower',
            field=models.BooleanField(default=False, help_text='Do you want to spend a point of willpower for an automatic succses?'),
        ),
        migrations.AlterField(
            model_name='activedisciplines',
            name='disciplines',
            field=models.ManyToManyField(blank=True, help_text='Which disciplines do you want to use during the downtime? (Hold down Ctrl to select multiple choices.)', to='players.DisciplineRating'),
        ),
        migrations.AlterField(
            model_name='aidaction',
            name='action',
            field=models.ForeignKey(help_text='What kind of action you are helping them with', on_delete=django.db.models.deletion.CASCADE, to='players.ActionType'),
        ),
        migrations.AlterField(
            model_name='aidaction',
            name='betrayal',
            field=models.BooleanField(default=False, help_text='Do you want to betray them rather than help them?'),
        ),
        migrations.AlterField(
            model_name='aidaction',
            name='helpee',
            field=models.ForeignKey(help_text='The person you are helping. (You are not allowed to chose your self.)', on_delete=django.db.models.deletion.CASCADE, related_name='help', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='aidaction',
            name='name',
            field=models.CharField(blank=True, help_text='if the action is targeting a hook, you need to enter the name of the hook here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='hooks',
            field=models.ManyToManyField(blank=True, related_name='master', to='players.Hook'),
        ),
        migrations.AlterField(
            model_name='character',
            name='political_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.PoliticalFaction'),
        ),
        migrations.AlterField(
            model_name='conservedomain',
            name='domain',
            field=models.ForeignKey(help_text='Which domain are you trying to conserve?', on_delete=django.db.models.deletion.CASCADE, to='players.Domain'),
        ),
        migrations.AlterField(
            model_name='conserveinfluence',
            name='influence',
            field=models.ForeignKey(help_text="Which of your influences are you trying to conserve? (Warning: Don't choose an influence where you have no hooks.)", on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='description',
            field=models.TextField(help_text='Describe how go about feeding.'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='What discipline (if any) do you use to feed?', null=True, on_delete=django.db.models.deletion.CASCADE, to='players.DisciplineRating'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='domain',
            field=models.ForeignKey(help_text='Where do you want to feed?', on_delete=django.db.models.deletion.CASCADE, to='players.Domain'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feeding_points',
            field=models.PositiveIntegerField(help_text='How many feeding points do you want to take from this domain?'),
        ),
        migrations.AlterField(
            model_name='influencedestroy',
            name='influence',
            field=models.ForeignKey(help_text='In what influence does the hook operate?', on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AlterField(
            model_name='influencedestroy',
            name='name',
            field=models.CharField(help_text='What is the name of the hook you are trying to destroy?', max_length=200),
        ),
        migrations.AlterField(
            model_name='influenceforge',
            name='influence',
            field=models.ForeignKey(help_text='In what influence area do you want to create a new hook? (warning: you may not take this action unless you have performed a Investigate Influence actiona for the influence area before. If you want to create a new influence area contact the gamemasters directly.)', on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AlterField(
            model_name='influenceforge',
            name='name',
            field=models.CharField(help_text='What is the name of the new hook?', max_length=200),
        ),
        migrations.AlterField(
            model_name='influencesteal',
            name='influence',
            field=models.ForeignKey(help_text='In what influence does the hook operate?', on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AlterField(
            model_name='influencesteal',
            name='name',
            field=models.CharField(help_text='What is the name of the hook you are trying to steal?', max_length=200),
        ),
        migrations.AlterField(
            model_name='investequipment',
            name='name',
            field=models.CharField(help_text='What kind of equipment is it?', max_length=200),
        ),
        migrations.AlterField(
            model_name='investequipment',
            name='specialization',
            field=models.ForeignKey(help_text='What specialization should it give as bonus?', on_delete=django.db.models.deletion.CASCADE, to='players.Specialization'),
        ),
        migrations.AlterField(
            model_name='investghoul',
            name='discipline',
            field=models.ForeignKey(help_text='What discipline should the ghoul gain a level in?', on_delete=django.db.models.deletion.CASCADE, to='players.Discipline'),
        ),
        migrations.AlterField(
            model_name='investghoul',
            name='name',
            field=models.CharField(help_text='What is the name of the ghoul you want to create, or improve?', max_length=200),
        ),
        migrations.AlterField(
            model_name='investghoul',
            name='specialization',
            field=models.ForeignKey(help_text='What specialization should the ghould gain?', on_delete=django.db.models.deletion.CASCADE, to='players.Specialization'),
        ),
        migrations.AlterField(
            model_name='investigatecharacterdowntimeactions',
            name='target',
            field=models.ForeignKey(help_text='Which character are you interested in?', on_delete=django.db.models.deletion.CASCADE, related_name='investigate_downtime_actions', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='investigatecharacterinfluence',
            name='target',
            field=models.ForeignKey(help_text='Which character are you interested in?', on_delete=django.db.models.deletion.CASCADE, related_name='investigate_influence', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='target',
            field=models.ForeignKey(help_text='Which character are you interested in?', on_delete=django.db.models.deletion.CASCADE, related_name='investigate_resources', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='investigateinfluence',
            name='influence',
            field=models.ForeignKey(help_text='What influence area are you interested in?', on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
        migrations.AlterField(
            model_name='investigatephenomenon',
            name='phenonemon',
            field=models.TextField(help_text='Describe what you want to learn. The more detailed you are the more detailed the information you get will be.'),
        ),
        migrations.AlterField(
            model_name='investweapon',
            name='weapon',
            field=models.ForeignKey(help_text='What weapon do you want to acqire?', on_delete=django.db.models.deletion.CASCADE, to='players.Weapon'),
        ),
        migrations.AlterField(
            model_name='keepersquestion',
            name='target',
            field=models.ForeignKey(help_text='Who do you want to question?', on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AlterField(
            model_name='learnattribute',
            name='attribute',
            field=models.ForeignKey(help_text='What attribute do you want to improve?', on_delete=django.db.models.deletion.CASCADE, to='players.Attribute'),
        ),
        migrations.AlterField(
            model_name='learnattribute',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='Do you have anyone to train you? If so, who?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttributeTrainee', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='learndiscipline',
            name='discipline',
            field=models.ForeignKey(help_text='What Discipline do you want to improve?', on_delete=django.db.models.deletion.CASCADE, to='players.Discipline'),
        ),
        migrations.AlterField(
            model_name='learndiscipline',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='Do you have anyone to train you? If so, who?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DisciplineTrainee', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='learnspecialization',
            name='new_specialization',
            field=models.ForeignKey(help_text='Which specialization do want to gain?', on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='players.Specialization'),
        ),
        migrations.AlterField(
            model_name='learnspecialization',
            name='old_specialization',
            field=models.ForeignKey(help_text='Which specialization are you willing to give up?', on_delete=django.db.models.deletion.CASCADE, related_name='forgeter', to='players.Specialization'),
        ),
        migrations.AlterField(
            model_name='learnspecialization',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='Do you have anyone to train you? If so, who?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SpecializationTrainee', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='mentorattribute',
            name='attribute',
            field=models.ForeignKey(help_text='What attribute do you want to help your student improve?', on_delete=django.db.models.deletion.CASCADE, to='players.Attribute'),
        ),
        migrations.AlterField(
            model_name='mentorattribute',
            name='student',
            field=models.ForeignKey(help_text='Who do you want to mentor?', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_teacher', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='mentordiscipline',
            name='discipline',
            field=models.ForeignKey(help_text='What discipline do you want to help your student improve?', on_delete=django.db.models.deletion.CASCADE, to='players.Discipline'),
        ),
        migrations.AlterField(
            model_name='mentordiscipline',
            name='student',
            field=models.ForeignKey(help_text='Who do you want to mentor?', on_delete=django.db.models.deletion.CASCADE, related_name='discipline_teacher', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='mentorspecialization',
            name='specialization',
            field=models.ForeignKey(help_text='What specialization do you want to help your student acquire?', on_delete=django.db.models.deletion.CASCADE, to='players.Specialization'),
        ),
        migrations.AlterField(
            model_name='mentorspecialization',
            name='student',
            field=models.ForeignKey(help_text='Who do you want to mentor?', on_delete=django.db.models.deletion.CASCADE, related_name='specialization_teacher', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='neglectdomain',
            name='domain',
            field=models.ForeignKey(help_text='Which domain do want to get an additional problem?', on_delete=django.db.models.deletion.CASCADE, to='players.Domain'),
        ),
        migrations.AlterField(
            model_name='patroldomain',
            name='domain',
            field=models.ForeignKey(help_text='Which domain do want to get one less problem?', on_delete=django.db.models.deletion.CASCADE, to='players.Domain'),
        ),
        migrations.AlterField(
            model_name='primogensaidaction',
            name='action',
            field=models.ForeignKey(help_text='What kind of action you are helping them with', on_delete=django.db.models.deletion.CASCADE, to='players.ActionType'),
        ),
        migrations.AlterField(
            model_name='primogensaidaction',
            name='betrayal',
            field=models.BooleanField(default=False, help_text='Do you want to betray rather than help?'),
        ),
        migrations.AlterField(
            model_name='primogensaidaction',
            name='helpee',
            field=models.ForeignKey(help_text='Who do you want to help? (You may only choose members of your own clan.)', on_delete=django.db.models.deletion.CASCADE, related_name='primogen_help', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='primogensaidaction',
            name='name',
            field=models.CharField(blank=True, help_text='if the action is targeting a hook, you need to enter the name of the hook here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='primogensquestion',
            name='target',
            field=models.ForeignKey(help_text='Who do you want to question? (You may only choose members of your own clan.)', on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
    
        migrations.DeleteModel(
            name='HistoricalPoliticalFraction',
        ),
        migrations.DeleteModel(
            name='PoliticalFraction',
        ),
                migrations.DeleteModel(
            name='HistoricalAction',
        ),
        migrations.DeleteModel(
            name='HistoricalActionOption',
        ),
        migrations.DeleteModel(
            name='HistoricalActionType',
        ),
        migrations.DeleteModel(
            name='HistoricalActiveDisciplines',
        ),
        migrations.DeleteModel(
            name='HistoricalAge',
        ),
        migrations.DeleteModel(
            name='HistoricalAttribute',
        ),
        migrations.DeleteModel(
            name='HistoricalAttributeRating',
        ),
        migrations.DeleteModel(
            name='HistoricalBoon',
        ),
        migrations.DeleteModel(
            name='HistoricalCanonFact',
        ),
        migrations.DeleteModel(
            name='HistoricalCharacter',
        ),
        migrations.DeleteModel(
            name='HistoricalClan',
        ),
        migrations.DeleteModel(
            name='HistoricalDiscipline',
        ),
        migrations.DeleteModel(
            name='HistoricalDisciplineRating',
        ),
        migrations.DeleteModel(
            name='HistoricalDomain',
        ),
        migrations.DeleteModel(
            name='HistoricalElderPower',
        ),
        migrations.DeleteModel(
            name='HistoricalExtraAction',
        ),
        migrations.DeleteModel(
            name='HistoricalFeeding',
        ),
        migrations.DeleteModel(
            name='HistoricalHook',
        ),
        migrations.DeleteModel(
            name='HistoricalHookAttribute',
        ),
        migrations.DeleteModel(
            name='HistoricalInfluence',
        ),
        migrations.DeleteModel(
            name='HistoricalInfluenceRating',
        ),
        migrations.DeleteModel(
            name='HistoricalNature',
        ),

        migrations.DeleteModel(
            name='HistoricalPopulation',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationship',
        ),
        migrations.DeleteModel(
            name='HistoricalRitual',
        ),
        migrations.DeleteModel(
            name='HistoricalRitualRating',
        ),
        migrations.DeleteModel(
            name='HistoricalSession',
        ),
        migrations.DeleteModel(
            name='HistoricalSpecialization',
        ),
        migrations.DeleteModel(
            name='HistoricalTitle',
        ),
        migrations.DeleteModel(
            name='HistoricalWeapon',
        ),
        migrations.DeleteModel(
            name='InfluenceList',
        ),
    ]
