# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_willpower',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
