# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_character_max_willpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='concept',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
