# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_hook_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='max_willpower',
        ),
        migrations.AddField(
            model_name='domain',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AddField(
            model_name='feeding',
            name='has_good_method',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='has_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='healing_aggrevated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='healing_bashing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='healing_lethal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='incident_roll',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='incidents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
