# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20170315_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='willpower',
            new_name='max_willpower',
        ),
    ]
