# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20170315_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='aggravated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='bashing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lethal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
