# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20170319_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_goal1', models.TextField()),
                ('open_goal2', models.TextField()),
                ('hidden_goal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_goal1', models.BooleanField(default=False)),
                ('open_goal2', models.BooleanField(default=False)),
                ('hidden_goal', models.BooleanField(default=False)),
                ('humanity_exp', models.BooleanField(default=False)),
                ('humanity', models.PositiveIntegerField(default=7)),
                ('max_willpower', models.PositiveIntegerField(default=0)),
                ('willpower', models.PositiveIntegerField(default=0)),
                ('blood', models.PositiveIntegerField(default=10)),
                ('bashing', models.PositiveIntegerField(default=0)),
                ('lethal', models.PositiveIntegerField(default=0)),
                ('aggravated', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HealingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bashing', models.PositiveIntegerField(default=0)),
                ('lethal', models.PositiveIntegerField(default=0)),
                ('aggrevated', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='heal_aggrevated',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='heal_bashing',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='heal_lethal',
        ),
    ]
