# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20170320_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreport',
            old_name='max_willpower',
            new_name='willpower_dots',
        ),
        migrations.RenameField(
            model_name='eventreport',
            old_name='willpower',
            new_name='willpower_points',
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='humanity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
