# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20170320_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='changegoals',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_goal', to='players.Character'),
        ),
        migrations.AddField(
            model_name='changegoals',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_goal', to='players.Session'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='players.Character'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='players.Session'),
        ),
        migrations.AddField(
            model_name='healingreport',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healing', to='players.Character'),
        ),
        migrations.AddField(
            model_name='healingreport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healing', to='players.Session'),
        ),
    ]
