# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_eventreport_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healingreport',
            old_name='aggrevated',
            new_name='aggravated',
        ),
    ]
