# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_actiontype_no_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='aid_action',
            field=models.BooleanField(default=False),
        ),
    ]
