# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-21 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_actiontype_aid_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
    ]
