# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_expdisciplinespending'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributerating',
            name='learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinerating',
            name='learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expdisciplinespending',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.DisciplineRating'),
        ),
    ]
