# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20170321_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpAttributeSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.BooleanField()),
                ('special_exp', models.PositiveIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.AttributeRating')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_atr_spending', to='players.Character')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_atr_spending', to='players.Session')),
            ],
        ),
    ]
