# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_expattributespending'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnattribute',
            name='blood',
            field=models.BooleanField(default=False, help_text='if you have someone to train you, do you drink of their blood?'),
        ),
        migrations.AddField(
            model_name='learndiscipline',
            name='blood',
            field=models.BooleanField(default=False, help_text='if you have someone to train you, do you drink of their blood?'),
        ),
        migrations.AddField(
            model_name='mentorattribute',
            name='blood',
            field=models.BooleanField(default=True, help_text='Do you give of your blood to your student?'),
        ),
        migrations.AddField(
            model_name='mentordiscipline',
            name='blood',
            field=models.BooleanField(default=True, help_text='Do you give of your blood to your student?'),
        ),
    ]
