# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_action_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Character')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Hook')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_hook', to='players.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='resolved',
            field=models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('PENDING', 'Pending'), ('Need GM attention', 'Need GM attention'), ('RESOLVED', 'Resolved')], default='UNRESOLVED', max_length=10),
        ),
    ]
