# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-31 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20170331_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Session'),
        ),
    ]
