# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20170406_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhoulDisciplineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Discipline')),
            ],
        ),
        migrations.RenameModel(
            old_name='HookAttribute',
            new_name='Aspect',
        ),
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='boons',
        ),
        migrations.RemoveField(
            model_name='character',
            name='canon_fact',
        ),
        migrations.RemoveField(
            model_name='character',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='character',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='frenzyTriggers',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ghouls',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hooks',
        ),
        migrations.RemoveField(
            model_name='disciplinerating',
            name='elder_powers',
        ),
        migrations.RemoveField(
            model_name='ghoul',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='attributerating',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AddField(
            model_name='disciplinerating',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AddField(
            model_name='elderpower',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.DisciplineRating'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AddField(
            model_name='ghoul',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghouls', to='players.Character'),
        ),
        migrations.AddField(
            model_name='hook',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='action',
            name='resolved',
            field=models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('PENDING', 'Pending'), ('GM', 'Need GM attention'), ('RESOLVED', 'Resolved')], default='UNRESOLVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rumor',
            name='rumor_type',
            field=models.CharField(choices=[('Influence', 'Influence'), ('Animal', 'Animal'), ('Faction', 'Faction'), ('Fact', 'Fact'), ('Character', 'Character')], default='Influence', max_length=15),
        ),
        migrations.AddField(
            model_name='ghouldisciplinerating',
            name='ghoul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Ghoul'),
        ),
    ]
