# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_auto_20170725_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Humanity', 'Humanity'), ('Clan Theme', 'Clan Theme'), ('Season Theme', 'Season Theme'), ('Nature', 'Nature'), ('Faction', 'Faction')], max_length=20)),
                ('belief', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='hidden_goal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='open_goal1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='open_goal2',
        ),
        migrations.AddField(
            model_name='goal',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
    ]
