# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20170726_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='open_goal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='belief',
            field=models.CharField(max_length=100),
        ),
    ]
