# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20170726_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Humanity', 'Humanity'), ('Clan Theme', 'Clan Theme'), ('Season Theme', 'Season Theme'), ('Nature', 'Nature'), ('Faction', 'Faction')], max_length=20)),
                ('belief', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('open_goal', models.BooleanField(default=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_goal', to='players.Character')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Goal')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_goal', to='players.Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='changegoals',
            name='character',
        ),
        migrations.RemoveField(
            model_name='changegoals',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChangeGoals',
        ),
    ]
