# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_session_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='resources',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='eventreport',
            old_name='resources',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='resources',
            new_name='assets',
        ),
        migrations.AlterField(
            model_name='investigatecharacterresources',
            name='target',
            field=models.ForeignKey(help_text='Which character are you interested in?', on_delete=django.db.models.deletion.CASCADE, related_name='investigate_assets', to='players.Character'),
        ),
    ]
