# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_auto_20170801_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hook',
            old_name='attributes',
            new_name='aspects',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(choices=[('superficial', 'superficial'), ('aggrevated', 'aggrevated')], max_length=200),
        ),
    ]
