# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20170801_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='lethal',
            new_name='superficial',
        ),
        migrations.RenameField(
            model_name='eventreport',
            old_name='lethal',
            new_name='superficial',
        ),
        migrations.RenameField(
            model_name='healingreport',
            old_name='lethal',
            new_name='superficial',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bashing',
        ),
        migrations.RemoveField(
            model_name='character',
            name='special_exp',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='bashing',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='willpower_dots',
        ),
        migrations.RemoveField(
            model_name='healingreport',
            name='bashing',
        ),
    ]
