# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20170801_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expattributespending',
            name='special_exp',
        ),
        migrations.RemoveField(
            model_name='expdisciplinespending',
            name='special_exp',
        ),
    ]
