# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_remove_character_demeanor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='helpers',
        ),
        migrations.RemoveField(
            model_name='aidaction',
            name='betrayal',
        ),
    ]
