# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_auto_20170801_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencepriority',
            name='influence',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='hooks',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority1',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority2',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority3',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority4',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority5',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority6',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority7',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterinfluence',
            name='priority8',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority1',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority2',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority3',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority4',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority5',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority6',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority7',
        ),
        migrations.RemoveField(
            model_name='investigatecharacterresources',
            name='priority8',
        ),
        migrations.DeleteModel(
            name='InfluencePriority',
        ),
        migrations.DeleteModel(
            name='ResourcePriority',
        ),
    ]
