# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_auto_20170801_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapons',
        ),
        migrations.AddField(
            model_name='character',
            name='firearms',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='melee',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AlterField(
            model_name='investweapon',
            name='weapon',
            field=models.CharField(choices=[('melee weapons', 'melee weapons'), ('firearms', 'firearms')], max_length=20),
        ),
    ]
