# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_auto_20170801_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='haven_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='haven_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Domain'),
        ),
        migrations.AddField(
            model_name='character',
            name='herd_description',
            field=models.TextField(blank=True),
        ),
    ]
