# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0041_auto_20170801_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghoul',
            old_name='character',
            new_name='master',
        ),
    ]
