# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_advantage_advantagerating_learnadvantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnadvantage',
            name='trainer',
        ),
        migrations.AddField(
            model_name='advantage',
            name='humanity',
            field=models.BooleanField(default=False),
        ),
    ]
