# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0045_auto_20170802_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreport',
            old_name='willpower_points',
            new_name='willpower',
        ),
    ]
