# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0046_auto_20170802_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpAdvantageSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.BooleanField()),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.AdvantageRating')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_adv_spending', to='players.Character')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_adv_spending', to='players.Session')),
            ],
        ),
    ]
