# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0047_expadvantagespending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='max_willpower',
        ),
    ]
