# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-04 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0051_remove_goal_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.CharField(max_length=10)),
                ('objective', models.CharField(max_length=10)),
                ('possessive', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
