# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-04 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0052_auto_20170804_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pronoun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Pronoun'),
        ),
    ]
