# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0054_auto_20170804_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
