# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0058_auto_20170805_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluenceWant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted', models.IntegerField(default=0)),
                ('dislodged', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencewant',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Character'),
        ),
        migrations.AddField(
            model_name='influencewant',
            name='influence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Influence'),
        ),
    ]
