# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0059_auto_20170805_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencewant',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
