# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-05 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0060_influencewant_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencewant',
            name='master',
        ),
    ]
