# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-05 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0061_remove_influencewant_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencewant',
            old_name='processed',
            new_name='final',
        ),
    ]
