# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0063_influencewant_elder'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='backgrounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='age',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
