# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0064_auto_20170806_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='allowed_on', to='players.Character'),
        ),
    ]
