# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-08 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0065_domain_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='has_permission',
        ),
    ]
