# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0067_auto_20170808_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
