# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0068_season_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraaction',
            name='action_options',
        ),
        migrations.RemoveField(
            model_name='extraaction',
            name='character',
        ),
        migrations.RemoveField(
            model_name='extraaction',
            name='session',
        ),
        migrations.AlterField(
            model_name='activedisciplines',
            name='disciplines',
            field=models.ManyToManyField(blank=True, help_text='Which disciplines do you want to use during the downtime?', to='players.Discipline'),
        ),
        migrations.DeleteModel(
            name='ExtraAction',
        ),
    ]
