# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0069_auto_20170809_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerating',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='players.Discipline'),
        ),
    ]
