# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0070_auto_20170809_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='What discipline (if any) do you use to feed?', null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Discipline'),
        ),
    ]
