# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0071_auto_20170809_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hook',
            name='influence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='players.Influence'),
        ),
        migrations.AddField(
            model_name='domain',
            name='place',
            field=models.ManyToManyField(blank=True, to='players.Place'),
        ),
    ]
