# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-16 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0072_auto_20170810_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='picture',
        ),
    ]
